%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clear all
tic;
global M_ oo_ exedet_ exdet_ recur_ recurs_ 
global options_ endval_
global ys0_ recurs0_ ex0_ ct_
options_ = [];
M_.fname = 'HST_Test2_AR2';
%
% Some global variables initialization
%
global_initialization;
diary off;
warning_old_state = warning;
warning off;
delete HST_Test2_AR2.log;
warning warning_old_state
logname_ = 'HST_Test2_AR2.log';
diary HST_Test2_AR2.log
options_.model_mode = 0;
erase_compiled_function('HST_Test2_AR2_static');
erase_compiled_function('HST_Test2_AR2_dynamic');
M_.exo_names = 'w1';
M_.exo_names_tex = '';
M_.exo_names = strvcat(M_.exo_names, 'w2');
M_.exo_names_tex = strvcat(M_.exo_names_tex, '');
M_.endo_names = 'c1';
M_.endo_names_tex = '';
M_.endo_names = strvcat(M_.endo_names, 'g1');
M_.endo_names_tex = strvcat(M_.endo_names_tex, '');
M_.endo_names = strvcat(M_.endo_names, 'i1');
M_.endo_names_tex = strvcat(M_.endo_names_tex, '');
M_.endo_names = strvcat(M_.endo_names, 'k1');
M_.endo_names_tex = strvcat(M_.endo_names_tex, '');
M_.endo_names = strvcat(M_.endo_names, 'd1');
M_.endo_names_tex = strvcat(M_.endo_names_tex, '');
M_.endo_names = strvcat(M_.endo_names, 'h1');
M_.endo_names_tex = strvcat(M_.endo_names_tex, '');
M_.endo_names = strvcat(M_.endo_names, 's1');
M_.endo_names_tex = strvcat(M_.endo_names_tex, '');
M_.endo_names = strvcat(M_.endo_names, 'b1');
M_.endo_names_tex = strvcat(M_.endo_names_tex, '');
M_.endo_names = strvcat(M_.endo_names, 'z2');
M_.endo_names_tex = strvcat(M_.endo_names_tex, '');
M_.endo_names = strvcat(M_.endo_names, 'z3');
M_.endo_names_tex = strvcat(M_.endo_names_tex, '');
M_.endo_names = strvcat(M_.endo_names, 'z4');
M_.endo_names_tex = strvcat(M_.endo_names_tex, '');
M_.endo_names = strvcat(M_.endo_names, 'z5');
M_.endo_names_tex = strvcat(M_.endo_names_tex, '');
M_.endo_names = strvcat(M_.endo_names, 'M_d1');
M_.endo_names_tex = strvcat(M_.endo_names_tex, '');
M_.endo_names = strvcat(M_.endo_names, 'M_h1');
M_.endo_names_tex = strvcat(M_.endo_names_tex, '');
M_.endo_names = strvcat(M_.endo_names, 'M_k1');
M_.endo_names_tex = strvcat(M_.endo_names_tex, '');
M_.endo_names = strvcat(M_.endo_names, 'M_s1');
M_.endo_names_tex = strvcat(M_.endo_names_tex, '');
M_.param_names = 'beta';
M_.param_names_tex = '';
M_.param_names = strvcat(M_.param_names, 'Phi_c_11');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'Phi_g_11');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'Phi_i_11');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'Gamma_11');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'Delta_k_11');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'Theta_k_11');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'Delta_h_11');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'Theta_h_11');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'Lambda_11');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'Pi_11');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'A22_11');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'A22_12');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'A22_13');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'A22_14');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'A22_15');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'A22_21');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'A22_22');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'A22_23');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'A22_24');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'A22_25');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'A22_31');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'A22_32');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'A22_33');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'A22_34');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'A22_35');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'A22_41');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'A22_42');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'A22_43');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'A22_44');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'A22_45');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'A22_51');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'A22_52');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'A22_53');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'A22_54');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'A22_55');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'C2_11');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'C2_12');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'C2_21');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'C2_22');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'C2_31');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'C2_32');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'C2_41');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'C2_42');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'C2_51');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'C2_52');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'U_b_11');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'U_b_12');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'U_b_13');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'U_b_14');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'U_b_15');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'U_d_11');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'U_d_12');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'U_d_13');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'U_d_14');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'U_d_15');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.param_names = strvcat(M_.param_names, 'z1');
M_.param_names_tex = strvcat(M_.param_names_tex, '');
M_.exo_det_nbr = 0;
M_.exo_nbr = 2;
M_.endo_nbr = 16;
M_.recur_nbr = 0;
M_.param_nbr = 57;
M_.Sigma_e = zeros(2, 2);
options_.linear = 1;
M_.lead_lag_incidence = [
	 0 7 0;
	 0 8 0;
	 0 9 0;
	 1 10 0;
	 0 11 0;
	 2 12 0;
	 0 13 0;
	 0 14 0;
	 3 15 0;
	 4 16 0;
	 5 17 0;
	 6 18 0;
	 0 19 23;
	 0 20 24;
	 0 21 25;
	 0 22 26;]';
M_.exo_names_orig_ord = [1:2];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(16, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(2, 1);
M_.params = repmat(NaN,57, 1);
M_.params( 1 ) = 0.952381;
beta = M_.params( 1 );
M_.params( 2 ) = 1;
Phi_c_11 = M_.params( 2 );
M_.params( 3 ) = 0;
Phi_g_11 = M_.params( 3 );
M_.params( 4 ) = 1;
Phi_i_11 = M_.params( 4 );
M_.params( 5 ) = 0.1;
Gamma_11 = M_.params( 5 );
M_.params( 6 ) = 0.95;
Delta_k_11 = M_.params( 6 );
M_.params( 7 ) = 1;
Theta_k_11 = M_.params( 7 );
M_.params( 8 ) = 0;
Delta_h_11 = M_.params( 8 );
M_.params( 9 ) = 1;
Theta_h_11 = M_.params( 9 );
M_.params( 10 ) = 0;
Lambda_11 = M_.params( 10 );
M_.params( 11 ) = 1;
Pi_11 = M_.params( 11 );
M_.params( 12 ) = 1;
A22_11 = M_.params( 12 );
M_.params( 13 ) = 0;
A22_12 = M_.params( 13 );
M_.params( 14 ) = 0;
A22_13 = M_.params( 14 );
M_.params( 15 ) = 0;
A22_14 = M_.params( 15 );
M_.params( 16 ) = 0;
A22_15 = M_.params( 16 );
M_.params( 17 ) = 0;
A22_21 = M_.params( 17 );
M_.params( 18 ) = 0.1;
A22_22 = M_.params( 18 );
M_.params( 19 ) = 0.2;
A22_23 = M_.params( 19 );
M_.params( 20 ) = 0;
A22_24 = M_.params( 20 );
M_.params( 21 ) = 0;
A22_25 = M_.params( 21 );
M_.params( 22 ) = 0;
A22_31 = M_.params( 22 );
M_.params( 23 ) = 1;
A22_32 = M_.params( 23 );
M_.params( 24 ) = 0;
A22_33 = M_.params( 24 );
M_.params( 25 ) = 0;
A22_34 = M_.params( 25 );
M_.params( 26 ) = 0;
A22_35 = M_.params( 26 );
M_.params( 27 ) = 0;
A22_41 = M_.params( 27 );
M_.params( 28 ) = 0;
A22_42 = M_.params( 28 );
M_.params( 29 ) = 0;
A22_43 = M_.params( 29 );
M_.params( 30 ) = 0.1;
A22_44 = M_.params( 30 );
M_.params( 31 ) = 0.2;
A22_45 = M_.params( 31 );
M_.params( 32 ) = 0;
A22_51 = M_.params( 32 );
M_.params( 33 ) = 0;
A22_52 = M_.params( 33 );
M_.params( 34 ) = 0;
A22_53 = M_.params( 34 );
M_.params( 35 ) = 1;
A22_54 = M_.params( 35 );
M_.params( 36 ) = 0;
A22_55 = M_.params( 36 );
M_.params( 37 ) = 0;
C2_11 = M_.params( 37 );
M_.params( 38 ) = 0;
C2_12 = M_.params( 38 );
M_.params( 39 ) = 1;
C2_21 = M_.params( 39 );
M_.params( 40 ) = 0;
C2_22 = M_.params( 40 );
M_.params( 41 ) = 0;
C2_31 = M_.params( 41 );
M_.params( 42 ) = 0;
C2_32 = M_.params( 42 );
M_.params( 43 ) = 0;
C2_41 = M_.params( 43 );
M_.params( 44 ) = 1;
C2_42 = M_.params( 44 );
M_.params( 45 ) = 0;
C2_51 = M_.params( 45 );
M_.params( 46 ) = 0;
C2_52 = M_.params( 46 );
M_.params( 47 ) = 30;
U_b_11 = M_.params( 47 );
M_.params( 48 ) = 0;
U_b_12 = M_.params( 48 );
M_.params( 49 ) = 0;
U_b_13 = M_.params( 49 );
M_.params( 50 ) = 0;
U_b_14 = M_.params( 50 );
M_.params( 51 ) = 0;
U_b_15 = M_.params( 51 );
M_.params( 52 ) = 5;
U_d_11 = M_.params( 52 );
M_.params( 53 ) = 1;
U_d_12 = M_.params( 53 );
M_.params( 54 ) = 0;
U_d_13 = M_.params( 54 );
M_.params( 55 ) = 1;
U_d_14 = M_.params( 55 );
M_.params( 56 ) = 0;
U_d_15 = M_.params( 56 );
M_.params( 57 ) = 1;
z1 = M_.params( 57 );
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (1)^2;
M_.Sigma_e(2, 2) = (1)^2;
steady;
options_.irf = 10;
options_.periods = 500;
options_.simul = 1;
var_list_=[];
info = stoch_simul(var_list_);
save('HST_Test2_AR2_results.mat', 'oo_');
diary off

disp(['Total computing time : ' dynsec2hms(toc) ]);
